from django.contrib import admin
from .models import Task, Solution, Guest, Usefulfiles, Guest_session, Like, Report, Vote, Subscription, Olympiad, Olympiad_part, Olympiad_task, Group, Group_student, Group_author_helper, Group_theme, Group_task, Article, Article_vote, Article_page
admin.site.register(Task)
admin.site.register(Solution)
admin.site.register(Guest)
admin.site.register(Usefulfiles)
admin.site.register(Guest_session)
admin.site.register(Like)
admin.site.register(Report)
admin.site.register(Vote)
admin.site.register(Subscription)
admin.site.register(Olympiad)
admin.site.register(Olympiad_part)
admin.site.register(Olympiad_task)
admin.site.register(Group)
admin.site.register(Group_student)
admin.site.register(Group_author_helper)
admin.site.register(Group_theme)
admin.site.register(Group_task)
admin.site.register(Article)
admin.site.register(Article_vote)
admin.site.register(Article_page)
# Register your models here.
