from django.urls import path

from . import views

app_name = 'math_book'
urlpatterns = [
path('', views.index, name='index'),
path('main/', views.index, name='index'),
path('index/', views.index, name='index'),
path('sendpost_subject', views.send_subject, name='send_subject'),
path('subject/create/', views.create_subject, name='create_subject'),
path('subject/<int:subject_id>/', views.get_subject, name='get_subject'),
path('subjects/', views.show_all_subject, name='show_all_subject'),
path('subjects/<str:sort_type>/', views.show_subject, name='show_subject'),
path('subjects/<str:sort_type>/page/<int:page_number>/', views.show_subject_page, name='show_subject_page'),
path('subject/<int:subject_id>/tickets/', views.show_all_tickets_from_subject, name='show_all_ticket'),
path('subject/<int:subject_id>/tickets/<str:sort_type>/', views.show_tickets_from_subject, name='show_ticket'),
path('subject/<int:subject_id>/tickets/<str:sort_type>/page/<int:page_number>/', views.show_tickets_from_subject_page, name='show_ticket_page'),
path('subject/<int:subject_id>/theorems/', views.show_all_theorems_from_subject, name='show_all_theorem'),
path('subject/<int:subject_id>/theorems/<str:sort_type>/', views.show_theorems_from_subject, name='show_theorem'),
path('subject/<int:subject_id>/theorems/<str:sort_type>/page/<int:page_number>/', views.show_theorems_from_subject_page, name='show_theorem_page'),
path('subject/<int:subject_id>/definitions/', views.show_all_definitions_from_subject, name='show_all_definition'),
path('subject/<int:subject_id>/definitions/<str:sort_type>/', views.show_definitions_from_subject, name='show_definition'),
path('subject/<int:subject_id>/definitions/<str:sort_type>/page/<int:page_number>/', views.show_definitions_from_subject_page, name='show_definition_page'),
path('sendpost_university', views.send_university, name='send_university'),
path('university/create/', views.create_university, name='create_university'),
path('university/<int:university_id>/', views.get_university, name='get_university'),
path('universitys/', views.show_all_university, name='show_all_university'),
path('universitys/<str:sort_type>/', views.show_university, name='show_university'),
path('universitys/<str:sort_type>/page/<int:page_number>/', views.show_university_page, name='show_university_page'),
path('university/<int:university_id>/tickets/', views.show_all_tickets_from_university, name='show_all_ticket'),
path('university/<int:university_id>/tickets/<str:sort_type>/', views.show_tickets_from_university, name='show_ticket'),
path('university/<int:university_id>/tickets/<str:sort_type>/page/<int:page_number>/', views.show_tickets_from_university_page, name='show_ticket_page'),
path('university/<int:university_id>/sessions/', views.show_all_sessions_from_university, name='show_all_session'),
path('university/<int:university_id>/sessions/<str:sort_type>/', views.show_sessions_from_university, name='show_session'),
path('university/<int:university_id>/sessions/<str:sort_type>/page/<int:page_number>/', views.show_sessions_from_university_page, name='show_session_page'),
path('sendpost_ticket', views.send_ticket, name='send_ticket'),
path('ticket/create/', views.create_ticket, name='create_ticket'),
path('ticket/<int:ticket_id>/', views.get_ticket, name='get_ticket'),
path('tickets/', views.show_all_ticket, name='show_all_ticket'),
path('tickets/<str:sort_type>/', views.show_ticket, name='show_ticket'),
path('tickets/<str:sort_type>/page/<int:page_number>/', views.show_ticket_page, name='show_ticket_page'),
path('ticket/<int:ticket_id>/vote_for/', views.send_vote_ticket, name='send_vote_ticket'),
path('ticket/<int:ticket_id>/vote_against/', views.send_vote_ticket, name='send_vote_ticket'),
path('sendpost_session', views.send_session, name='send_session'),
path('session/create/', views.create_session, name='create_session'),
path('session/<int:session_id>/', views.get_session, name='get_session'),
path('sessions/', views.show_all_session, name='show_all_session'),
path('sessions/<str:sort_type>/', views.show_session, name='show_session'),
path('sessions/<str:sort_type>/page/<int:page_number>/', views.show_session_page, name='show_session_page'),
path('sendpost_theorem', views.send_theorem, name='send_theorem'),
path('theorem/create/', views.create_theorem, name='create_theorem'),
path('theorem/<int:theorem_id>/', views.get_theorem, name='get_theorem'),
path('theorems/', views.show_all_theorem, name='show_all_theorem'),
path('theorems/<str:sort_type>/', views.show_theorem, name='show_theorem'),
path('theorems/<str:sort_type>/page/<int:page_number>/', views.show_theorem_page, name='show_theorem_page'),
path('theorem/<int:theorem_id>/vote_for/', views.send_vote_theorem, name='send_vote_theorem'),
path('theorem/<int:theorem_id>/vote_against/', views.send_vote_theorem, name='send_vote_theorem'),
path('sendpost_definition', views.send_definition, name='send_definition'),
path('definition/create/', views.create_definition, name='create_definition'),
path('definition/<int:definition_id>/', views.get_definition, name='get_definition'),
path('definitions/', views.show_all_definition, name='show_all_definition'),
path('definitions/<str:sort_type>/', views.show_definition, name='show_definition'),
path('definitions/<str:sort_type>/page/<int:page_number>/', views.show_definition_page, name='show_definition_page'),
path('definition/<int:definition_id>/vote_for/', views.send_vote_definition, name='send_vote_definition'),
path('definition/<int:definition_id>/vote_against/', views.send_vote_definition, name='send_vote_definition'),

]