# Generated by Django 3.2.4 on 2021-09-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='class_name',
            field=models.CharField(default='11', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='theme1_name',
            field=models.CharField(default='No theme', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='theme2_name',
            field=models.CharField(default='No theme', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.CharField(max_length=1000),
        ),
    ]
