# Generated by Django 3.2.4 on 2021-09-20 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0002_auto_20210920_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creator_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='physicsesc.guest'),
        ),
    ]
