# Generated by Django 3.2.4 on 2021-09-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0003_task_creator_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='guest_password',
            field=models.CharField(default='1234', max_length=40),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_text',
            field=models.CharField(max_length=500),
        ),
    ]
