# Generated by Django 3.2.4 on 2021-10-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0004_auto_20210927_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
