# Generated by Django 3.2.4 on 2021-10-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0005_task_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='report',
            field=models.IntegerField(default=0),
        ),
    ]
