# Generated by Django 3.2.4 on 2021-10-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0006_task_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='picture_href',
            field=models.CharField(default='no', max_length=100),
        ),
    ]
