# Generated by Django 3.2.4 on 2021-10-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0008_usefulfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usefulfiles',
            name='href',
        ),
        migrations.RemoveField(
            model_name='usefulfiles',
            name='name',
        ),
        migrations.AddField(
            model_name='usefulfiles',
            name='file_href',
            field=models.CharField(default='no name', max_length=200),
        ),
        migrations.AddField(
            model_name='usefulfiles',
            name='file_name',
            field=models.CharField(default='no name', max_length=50),
        ),
    ]
