# Generated by Django 3.2.4 on 2021-10-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0009_auto_20211021_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='guest_rights',
            field=models.IntegerField(default=0),
        ),
    ]
