# Generated by Django 3.2.4 on 2021-10-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0010_guest_guest_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='no name', max_length=50),
        ),
    ]
