# Generated by Django 3.2.4 on 2021-10-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0011_task_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='picture_href',
            field=models.CharField(default='https://rkn.gov.ru/', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.CharField(max_length=1500),
        ),
    ]
