# Generated by Django 4.0.2 on 2022-06-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0012_auto_20211031_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='votes',
            new_name='votes_count',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='like',
            new_name='like_count',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='report',
            new_name='report_count',
        ),
        migrations.AddField(
            model_name='solution',
            name='votes_against_count',
            field=models.IntegerField(default=0),
        ),
    ]
