# Generated by Django 4.0.2 on 2022-06-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0013_rename_votes_solution_votes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='creator_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='physicsesc.guest'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.BooleanField(default=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicsesc.guest')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicsesc.solution')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicsesc.task')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicsesc.guest')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicsesc.task')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicsesc.guest')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicsesc.task')),
            ],
        ),
    ]
