# Generated by Django 4.0.2 on 2022-06-09 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0014_solution_creator_id_vote_report_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicsesc.guest')),
            ],
        ),
    ]
