# Generated by Django 4.0.2 on 2022-06-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0015_guest_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='guest_information',
            field=models.CharField(default='no information', max_length=2000),
        ),
    ]
