# Generated by Django 4.0.2 on 2022-06-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0016_guest_guest_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest_session',
            name='HTTP_USER_AGENT',
            field=models.CharField(default='no name', max_length=500),
        ),
        migrations.AddField(
            model_name='guest_session',
            name='computername',
            field=models.CharField(default='no name', max_length=100),
        ),
        migrations.AddField(
            model_name='guest_session',
            name='os',
            field=models.CharField(default='no name', max_length=100),
        ),
    ]
