# Generated by Django 4.0.2 on 2022-06-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0017_guest_session_http_user_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='subscriber_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guest',
            name='subscription_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField(default=1)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicsesc.guest')),
            ],
        ),
    ]
