# Generated by Django 4.0.2 on 2022-06-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0019_guest_task_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='guest_icon_href',
            field=models.CharField(default='https://no', max_length=200),
        ),
    ]
