# Generated by Django 4.0.2 on 2022-06-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0020_guest_guest_icon_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olympiad_name', models.CharField(default='no name', max_length=100)),
                ('olympiad_description', models.CharField(default='no information', max_length=2000)),
                ('olympiad_site_link', models.CharField(default='no link', max_length=200)),
                ('olympiad_part_count', models.IntegerField(default=1)),
                ('olympiad_participant_count', models.IntegerField(default=0)),
                ('olympiad_level', models.IntegerField(default=4)),
                ('class_name', models.IntegerField(default=11)),
                ('olympiad_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicsesc.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Olympiad_part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olympiad_part_description', models.CharField(default='no information', max_length=2000)),
                ('olympiad_part_site_link', models.CharField(default='no link', max_length=200)),
                ('olympiad_part_number', models.IntegerField(default=1)),
                ('olympiad_task_count', models.IntegerField(default=1)),
                ('olympiad_part_participant_count', models.IntegerField(default=0)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicsesc.olympiad')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.CharField(max_length=3000),
        ),
        migrations.CreateModel(
            name='Olympiad_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.IntegerField(default=1)),
                ('task_name', models.CharField(default='no name', max_length=50)),
                ('task_text', models.CharField(max_length=3000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('task_score', models.IntegerField(default=1)),
                ('theme1_name', models.CharField(default='No theme', max_length=30)),
                ('theme2_name', models.CharField(default='No theme', max_length=30)),
                ('picture_href', models.CharField(default='https://rkn.gov.ru/', max_length=100)),
                ('creator_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='physicsesc.guest')),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicsesc.olympiad')),
                ('olympiad_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicsesc.olympiad_part')),
            ],
        ),
    ]
