# Generated by Django 4.0.2 on 2022-06-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0022_task_task_type_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_helper_count', models.IntegerField(default=0)),
                ('group_description', models.CharField(default='no description', max_length=3000)),
                ('group_type_password', models.BooleanField(default=False)),
                ('group_password', models.CharField(default='1234', max_length=50)),
                ('group_private_type', models.BooleanField(default=False)),
                ('group_application_type', models.BooleanField(default=False)),
                ('student_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicsesc.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Group_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicsesc.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicsesc.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Group_author_helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.BooleanField(default=False)),
                ('author_helper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicsesc.guest')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physicsesc.group')),
            ],
        ),
    ]
