# Generated by Django 4.0.2 on 2022-06-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0023_group_group_student_group_author_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_name',
            field=models.CharField(default='no name', max_length=50),
        ),
        migrations.AddField(
            model_name='group',
            name='picture_href',
            field=models.CharField(default='https://rkn.gov.ru/', max_length=100),
        ),
    ]
