# Generated by Django 4.0.2 on 2022-06-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physicsesc', '0026_rename_class_name_olympiad_olympiad_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_theme',
            name='group_theme_description',
            field=models.CharField(default='no description', max_length=3000),
        ),
    ]
