from django.urls import path

from . import views
app_name= "physicsesc"
urlpatterns = [
path('', views.index, name='index'),
path('main/', views.main, name='main'),
path('main/page/<int:page_number>/', views.main_page, name='main'),
path('new/', views.new, name='new'),
path('new/page/<int:page_number>/', views.new_page, name='new'),
path('best',views.best, name="best"),
path('best/page/<int:page_number>/', views.best_page, name="best"),
path('login', views.login, name='login'),
path('theme', views.theme, name='theme'),
path('themepost', views.themepost, name='themepost'),
path('theme/<str:theme_name1>', views.themefind, name='themefind'),
path('theme/<str:theme_name1>/<str:theme_name2>', views.themefind2, name='themefind2'),
path('user', views.user, name='user'),
path('user/<str:user_name>', views.userfind, name='userfind'),
path('sendaccountpost',views.sendaccountpost, name='sendaccountpost'),
#path('sendaccount/<str:guest_name>/<str:guest_password>', views.sendaccount, name='sendaccount'),
path('createtask/', views.createtask, name='createtask'),
path('sendtask', views.sendtaskpost, name = 'sendtaskpost'),
path('<int:task_id>/', views.task, name='task'),
path('<int:task_id>/like', views.like, name='like'),
path('<int:task_id>/report', views.report, name='report'),
path('<int:task_id>/solution/', views.solution, name='solution'),
path('<int:task_id>/solution/<int:solution_id>/<str:vote_type>/', views.solution_vote, name='solution_vote'),
path('<int:task_id>/makesolution/', views.makesolution, name='makesolution'),
#path('<int:task_id>/makesolution2/', views.makesolution2, name='makesolution2'),
#path('<int:task_id>/makesolution3/<str:solution_text>', views.makesolution3, name='makesolution3'),
path('sendsolutionpost', views.sendsolutionpost, name='sendsolutionpost'),
#path('sendtask/<str:task_text>/<str:creator_name>/<str:creator_password>/<str:theme1_name>/<str:theme2_name>', views.sendtask, name='sendtask'),
#path('sendtask/<str:task_text>/<str:creator_name>/<str:creator_password>/<str:theme1_name>/<str:theme2_name>/<str:picture_url>', views.sendtaskwithpicture, name='sendtaskwithpicture'),
path('useful', views.useful, name='useful'),
path('sendusefulfile',views.sendusefulfile,name="sendusefulfile"),
path('account/<str:user_name>', views.account, name='account'),
path('myaccount/', views.myaccount, name='myaccount'),
path('settings/', views.settings, name='settings'),

]