from django.urls import path

from . import views
app_name= "physicsesc"
urlpatterns = [
path('', views.main, name='main'),
path('main/', views.main, name='main'),
path('task/', views.maintask, name='main'),
path('task/page/<int:page_number>/', views.maintask_page, name='main'),
path('new/', views.new, name='new'),
path('new/page/<int:page_number>/', views.new_page, name='new'),
path('best/', views.best, name="best"),
path('best/page/<int:page_number>/', views.best_page, name="best"),
path('my/', views.my, name="my"),
path('my/page/<int:page_number>/', views.my_page, name="my"),
path('login', views.login, name='login'),
path('theme', views.theme, name='theme'),
path('themepost', views.themepost, name='themepost'),
path('theme/<str:theme_name1>', views.themefind, name='themefind'),
path('theme/<str:theme_name1>/<str:theme_name2>', views.themefind2, name='themefind2'),
path('class/<int:class_name>', views.classfind, name='classfind'),
path('user', views.user, name='user'),
path('user/<str:user_name>', views.userfind, name='userfind'),
path('user/<str:user_name>/', views.userfind, name='userfind'),
path('sendaccountpost',views.sendaccountpost, name='sendaccountpost'),
#path('sendaccount/<str:guest_name>/<str:guest_password>', views.sendaccount, name='sendaccount'),
path('createtask/', views.createtask, name='createtask'),
path('sendtask', views.sendtaskpost, name = 'sendtaskpost'),
path('<int:task_id>/', views.task, name='task'),
path('<int:task_id>/delete', views.task_delete, name='task_delete'),
path('<int:task_id>/like', views.like, name='like'),
path('<int:task_id>/report', views.report, name='report'),
path('<int:task_id>/solution/', views.solution, name='solution'),
path('<int:task_id>/solution/<int:solution_id>/<str:vote_type>/', views.solution_vote, name='solution_vote'),
path('<int:task_id>/makesolution/', views.makesolution, name='makesolution'),
#path('<int:task_id>/makesolution2/', views.makesolution2, name='makesolution2'),
#path('<int:task_id>/makesolution3/<str:solution_text>', views.makesolution3, name='makesolution3'),
path('sendsolutionpost', views.sendsolutionpost, name='sendsolutionpost'),
#path('sendtask/<str:task_text>/<str:creator_name>/<str:creator_password>/<str:theme1_name>/<str:theme2_name>', views.sendtask, name='sendtask'),
#path('sendtask/<str:task_text>/<str:creator_name>/<str:creator_password>/<str:theme1_name>/<str:theme2_name>/<str:picture_url>', views.sendtaskwithpicture, name='sendtaskwithpicture'),
path('useful', views.useful, name='useful'),
path('useful/', views.useful, name='useful'),
path('sendusefulfile',views.sendusefulfile,name="sendusefulfile"),
path('account/<str:user_name>/', views.account, name='account'),
path('account/<str:user_name>/makesubscribe', views.makesubscribe, name='makesubscribe'),
path('account/<str:user_name>/unsubscribe', views.unsubscribe, name='unsubscribe'),
path('subscribes/', views.subscribes, name='subscribes'),
path('subscribes/page/<int:page_number>/', views.subscribes_page, name='subscribes_page'),
path('subscribers/', views.subscribers, name='subscribers'),
path('subscribers/page/<int:page_number>/', views.subscribers_page, name='subscribers_page'),
path('myaccount/', views.myaccount, name='myaccount'),
path('settings/', views.settings, name='settings'),
path('settings/closesession/<str:session_key>', views.closesession, name='closesession'),
path('changeaccountinformation', views.changeaccountinformation, name='changeaccountinformation'),
path("changepassword", views.changepassword, name='changepassword'),
path("changecolortheme", views.changecolortheme, name="changecolortheme"),


path("chats/", views.private_chats),
path("chats/page/<int:page_number>/", views.private_chats_page),
path("chats/private/", views.private_chats),
path("chats/private/page/<int:page_number>/", views.private_chats_page),
path("chat/user/<str:user_name>/", views.private_chat),
path("chat/user/<str:user_name>/page/<int:page_number>/", views.private_chat_page),
path('sendprivatemessagepost', views.sendprivatemessagepost, name='sendprivatemessagepost'),

path('olympiad/', views.olympiad, name='olympiad'),
path('olympiad/page/<int:page_number>/', views.olympiad_page, name='olympiad_page'),

path('group/', views.all_group, name='group'),
path('group/page/<int:page_number>/', views.all_group_page, name='group_page'),
path('group/new/', views.new_group, name='group'),
path('group/new/page/<int:page_number>/', views.new_group_page, name='group_page'),
path('group/popular/', views.popular_group, name='group'),
path('group/popular/page/<int:page_number>/', views.popular_group_page, name='group_page'),
path('group/find/', views.groupfind, name='groupfind'),
path('group/my/', views.my_group, name='my_group'),
path('group/my/page/<int:page_number>/', views.my_group_page, name='my_group_page'),
path('group/student/', views.student_group, name='student_group'),
path('group/student/page/<int:page_number>/', views.student_group_page, name='student_group_page'),

path('group/creategroup/', views.creategroup, name='creategroup'),
path('sendgrouppost', views.sendgrouppost, name='sendgrouppost'),
path('group/<int:group_id>/', views.thisgroup, name='group'),
path('group/<int:group_id>/page/<int:page_number>/', views.group_page, name='group_page'),
path('group/<int:group_id>/creategrouptask/', views.creategrouptask, name='creategrouptask'),
path('sendgrouptaskpost', views.sendgrouptaskpost, name='sendgrouptaskpost'),
path('group/<int:group_id>/theme/', views.grouptheme, name='grouptheme'),
path('group/<int:group_id>/theme/page/<int:page_number>/', views.grouptheme_page, name='grouptheme_page'),
path('group/<int:group_id>/theme/<str:theme_name>/', views.groupthemetask, name='groupthemetask'),
path('group/<int:group_id>/theme/<str:theme_name>/page/<int:page_number>/', views.groupthemetask_page, name='groupthemetask_page'),
path('group/<int:group_id>/creategrouptheme/', views.creategrouptheme, name='creategrouptheme'),
path('sendgroupthemepost', views.sendgroupthemepost, name='sendgroupthemepost'),
path('sendgroupapplicationpost', views.sendgroupapplicationpost, name='sendgroupapplicationpost'),
path('group/<int:group_id>/groupapplication/', views.groupapplication, name='groupapplication'),
path('group/<int:group_id>/groupapplication/<str:user_name>/<str:approve_type>', views.approvegroupapplication, name='approvegroupapplication'),
path('group/<int:group_id>/groupparticipant/', views.groupparticipant, name='groupparticipant'),
path('group/<int:group_id>/groupparticipant/<str:user_name>/<str:approve_type>', views.approvegroupparticipant, name='approvegroupparticipant'),

path('livephysics/', views.livephysics, name='livephysics'),
path('livephysicsshow', views.livephysicsshow, name='livephysicsshow'),

path('articles/', views.articles1, name='article1'),
path('articles/createarticle/', views.createarticle, name='createarticle'),
path('articles/theme/<str:theme_name>/', views.articletheme, name='articletheme'),
path('articles/<str:page_name>/', views.articles, name='article'),
path('articles/<str:page_name>/page/<int:page_number>/', views.articles_page, name='articles_page'),
path('sendarticlepost', views.sendarticlepost, name='sendarticlepost'),
path('article/createarticle/', views.createarticle, name='createarticle'),
path('article/<int:article_id>/', views.article, name='article'),
path('article/<int:article_id>/view/', views.article_view, name='create_article'),
path('article/<int:article_id>/<str:vote_type>/', views.article_vote, name='article_vote'),
]