# Generated by Django 4.0.2 on 2023-07-21 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='no name', max_length=100)),
                ('hashed_password', models.IntegerField(default=0)),
                ('about', models.TextField(default='no information', max_length=5000)),
                ('pub_date', models.DateTimeField(verbose_name='date created')),
                ('icon', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_0_not_checked_messages_count', models.IntegerField(default=0)),
                ('author_1_not_checked_messages_count', models.IntegerField(default=0)),
                ('author_0_notifications', models.BooleanField(default=False)),
                ('author_1_notifications', models.BooleanField(default=False)),
                ('author_0_ban_chat', models.BooleanField(default=False)),
                ('author_1_ban_chat', models.BooleanField(default=False)),
                ('messages_count', models.IntegerField(default=0)),
                ('authors', models.ManyToManyField(to='matmech_messenger.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='no text', max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date created')),
                ('is_answer', models.BooleanField(default=False)),
                ('answers_count', models.IntegerField(default=0)),
                ('is_read', models.BooleanField(default=False)),
                ('answer_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matmech_messenger.privatemessage')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matmech_messenger.guest')),
                ('private_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matmech_messenger.privatechat')),
            ],
        ),
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(default='its impossible', max_length=100)),
                ('http_user_agent', models.TextField(default='its impossible', max_length=500)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matmech_messenger.guest')),
            ],
        ),
    ]
