# Generated by Django 3.2.4 on 2021-11-01 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(default='no name', max_length=100)),
                ('room_theme', models.CharField(default='No theme', max_length=50)),
                ('room_rights', models.IntegerField(default=0)),
                ('room_type_private', models.BooleanField(default=False)),
                ('room_type_password', models.BooleanField(default=False)),
                ('room_type_token', models.BooleanField(default=False)),
                ('room_password', models.CharField(default='no password', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('message_text', models.CharField(default='empty message', max_length=1000)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anonimnetwork.room')),
            ],
        ),
    ]
