# Generated by Django 3.2.4 on 2021-12-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonimnetwork', '0002_message_answer_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.CharField(default='empty message', max_length=300),
        ),
    ]
