# Generated by Django 4.0.2 on 2022-03-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonimnetwork', '0003_alter_message_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_description',
            field=models.CharField(default='no description', max_length=500),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.CharField(default='empty message', max_length=1000),
        ),
    ]
