# Generated by Django 4.0.2 on 2022-03-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonimnetwork', '0004_room_room_description_alter_message_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type_channel',
            field=models.BooleanField(default=False),
        ),
    ]
