# Generated by Django 4.0.2 on 2022-03-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonimnetwork', '0006_room_room_channel_admin_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_text',
            field=models.CharField(default='empty message', max_length=2000),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_description',
            field=models.CharField(default='no description', max_length=1000),
        ),
    ]
