# Generated by Django 4.0.2 on 2022-04-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonimnetwork', '0007_message_is_pinned_alter_message_message_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_messages_count',
            field=models.IntegerField(default=0),
        ),
    ]
