# Generated by Django 4.0.2 on 2022-05-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonimnetwork', '0008_room_room_messages_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='answers_count',
            field=models.IntegerField(default=0),
        ),
    ]
